// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBjQF_3Azc8ftdG1DTmrpecr8mSW7ZvGxo',
    appId: '1:986311368980:web:a79872ae3d1edde5d9e201',
    messagingSenderId: '986311368980',
    projectId: 'confab-8e5f4',
    authDomain: 'confab-8e5f4.firebaseapp.com',
    storageBucket: 'confab-8e5f4.appspot.com',
    measurementId: 'G-KJ1GQ20113',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBLFsHDmJch_tpCuKGFVuED8gvf0J1PfYc',
    appId: '1:986311368980:android:71b2a39274da117ed9e201',
    messagingSenderId: '986311368980',
    projectId: 'confab-8e5f4',
    storageBucket: 'confab-8e5f4.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA48mLyRKkNEo4UI07uyk8Qf5M_hlNO344',
    appId: '1:986311368980:ios:df06898acb75ce6cd9e201',
    messagingSenderId: '986311368980',
    projectId: 'confab-8e5f4',
    storageBucket: 'confab-8e5f4.appspot.com',
    iosClientId: '986311368980-5r7tk570mdifm8lhh3n9dkt4lpd7cf9m.apps.googleusercontent.com',
    iosBundleId: 'com.example.confab',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA48mLyRKkNEo4UI07uyk8Qf5M_hlNO344',
    appId: '1:986311368980:ios:2cc992e1a96fb506d9e201',
    messagingSenderId: '986311368980',
    projectId: 'confab-8e5f4',
    storageBucket: 'confab-8e5f4.appspot.com',
    iosClientId: '986311368980-0rbhimhk936r3iolr507m75h0ij4rs3v.apps.googleusercontent.com',
    iosBundleId: 'com.example.confab.RunnerTests',
  );
}
